language: node_js
node_js:
  - "0.11"
  - "0.10"
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
services:
  - mongodb
  - redis-server
after_script:
  NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
