language: node_js
node_js:
  - "0.11"
addons:
  code_climate:
    repo_token: d771593b3584d50f78c5bf92c9b9e766412eccb323f82e934f2bdbc1f5b3f6f8
services:
  - mongodb
  - redis-server
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
after_script:
  - cat coverage/lcov.info | codeclimate
